### PR TITLE
Put language information in separate json files

### PR DESCRIPTION
**Pull request by xZise**
Instead of having one large file, this separates the translations into each language. This always to determine which languages are available and also to dynamically use another translation (like the English) if the translation is not available for the selected language.

### CODE REVIEW

**Comment by xZise** [comment]
We could maybe find more sensible identifiers (e.g. instead of `*-balloon` have `balloon-*`).

**Comment by xZise** [comment]
Okay there seems to be an mistake in it actually… so I'd prefer it not be merged yet (apart from the fact that we should maybe rethink the identifiers).

**Comment by xZise** [comment]
Okay found the issue and fixed that… not sure if there are more sensible names. There are some entries which aren't used anywhere so I don't know what we can use there (or maybe drop them?). Anyway I reopen it to update the commit.

**Comment by espinosaluis** [comment]
There is an issue that it seems that it was already there that if you change to a different route, the language goes back to English.

**Comment by xZise** [comment]
I'm going to look into that. One question though: How did you change the language? Using that little configuration window? And you didn't need to login in between?

**Comment by espinosaluis** [comment]
You change the language by clicking on "Show Config"
I have noticed now that when I click there, under language says "Deutsch (German)" even if I'm seeing everything in English.

Once you change the language try to change to a different route, and you will see that the text defaults to English.

**Comment by xZise** [comment]
Okay that it always selects the first language (it searches through the `i18n` directory and is using that ordering which is mostly alphabetically using the code) is a bug and hadn't noticed that. I'll look into that as well.

I am also able to replicate your issue so it should be possible for me to find the issue.

**Comment by xZise** [comment]
Ah that it always selects the first language is because no language is set (and it defaults to English) as it won't “preselect” any language and it defaults to the first one.

**Comment by xZise** [comment]
Okay the preselection issue is fixed with #57. And the other issue is simply due to the fact that it'll default to the language "english" unless there has been a `language` parameter in the request. But it is actually using a `storelanguage` parameter in the subsequent requests.

**Comment by espinosaluis** [comment]
Ok. Thanks.

**Pull request merged**
