### PR TITLE
Revert "Calculate marker information in JavaScript"

### PR DESCRIPTION
**Pull request by espinosaluis**
Reverts espinosaluis/TrackMeViewer#73

### CODE REVIEW

**Comment by espinosaluis** [comment]
Bugs found:
- Time Traveled is missing a digit.
- Avd. Speed doesn't match with older version.

**New version**
new

**Old version**
old

**Comment by xZise** [comment]
Well 89281bd4 changed the average speed to use the actual average speed, not sure what your intentions are related to that.

**Comment by xZise** [comment]
The reason why I didn't add the leading zero on the hours is that the number (different to the minutes and seconds) can be three digits wide. So how do you want it, because before that number could only be 00 to 23 but now it can be any hole positive number (including 0).

**Comment by espinosaluis** [comment]
Ok, it sounds good then. However about the second issue, I would rather not see a leading single 0 when the time travel is less than 1 hour. It just looks weird, We should have something like this:
- Less than 1 hour. Examples:
  00:45:40
  00:07:23
  00:03:03
- Less than 100 hours:
  01:02:40
  50:06:59
  97:23:11
- More than 99 hours
  100:23.42
  150:45:56

**Comment by xZise** [comment]
So “not see a leading single 0 digit” just means that you want it to use at least two digits but more if necessary?

**Comment by espinosaluis** [comment]
Yes.

**Pull request merged**
