### PR TITLE
Revert "Convert download script"

### PR DESCRIPTION
**Pull request by espinosaluis**
Reverts espinosaluis/TrackMeViewer#67

xZise,

Sorry for the long delay. I had surgery and I haven't been able to go back to this until now.

I just tried this but I'm getting a "Duplicate headers received from server
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION" error message when I click on "Download - KML format" 
It seems to work for most of the routes and I think it's related to not being able to process certain characters. For example, if the name contains the character "ï", it fails.

By the way, the export.php seems to be broken, too. No matter what I enter, I always get the error:

Parse error: syntax error, unexpected T_IF in /home/content/l/u/i/luisespinosa/html/trbeta/export.php on line 15

Thanks.

### CODE REVIEW

**Comment by xZise** [comment]
I was not available myself for almost three months so I wasn't able to look into this.

Anyway I already noted in d8b4ce65 that I don't know what the problem with the export script is. Now you mentioned it here so I can take a look and hopefully I can provide a fix for both problems.

**Comment by espinosaluis** [comment]
Thanks.

**Comment by xZise** [comment]
Okay I found the issue for that particular problem with the export script but can't guarantee that there isn't another issue (as it seems I haven't tested it at all 😕).

**Comment by xZise** [comment]
And the download script issue doesn't looks like it is related to my change actually. If you look at http://stackoverflow.com/a/25844041 it seems related to the following line:

```
header("Content-Disposition:attachment;filename=" . $FileName); 
```

But my patch doesn't change that line (or how `$FileName` is defined) so it should also happen without it. Still I'm going to look into that issue and maybe the common denominator is something different in your case.

Do you have the trip names of some trips that do work and of those that do not work?

**Comment by espinosaluis** [comment]
It seems that export.php works now.
I don't remember what route was causing the issue, but I tried a few ones with accented characters and seems to work, too.

Thanks for your help.

**Pull request merged**
