### PR TITLE
Use markers having photo or comment (#10)

### PR DESCRIPTION
**Pull request by xZise**
This is using the yellow instead of grey marker to highlight markers which have
a photo or comment associated with it.

### CODE REVIEW

**Comment by espinosaluis** [comment]
Thanks!

**Comment by espinosaluis** [comment]
Could be possible to change the markers with comments to purple so it will match with the ones displayed on the TrackMe client for Android? Thanks.

**Comment by xZise** [comment]
Okay I have recreated the marker symbol with SVG so we can create new ones in any color. But I'd first like to update the Google Maps JavaScript API to version 3, as it's easier there to add icons. It might be possible with version 2 but there is no documentation anymore :(

**Comment by xZise** [comment]
Okay I just noticed you already uploaded a patch. In that case, 086eb83d162e4fad13562f508a6562ac8d5e0abb is changing the icon for both types. I thought you only want the purple marker for comments and the yellow for photos?

**Comment by espinosaluis** [comment]
Yes, I made that change a few hours ago. For photos I want to show the Camera icon, even if the position already contains a comment.

**Comment by xZise** [comment]
Well that shouldn't be a problem and #25 is preparing that so that you just need to replace one variable. Although to be honest I'd suggest to merge #23 before you are going to use the actual camera icon as you can there just use the URL (as mentioned in my comment above). But how you handle it, is you choice.

**Pull request merged**
