### PR TITLE
Don't query count and average separately

### PR DESCRIPTION
**Pull request by xZise**
Instead of doing three queries, to get the positions, average speed and number of positions, it can just query the positions and determine the other two values by counting the positions and averaging the speeds of them.

The calculation of the average speed will be moved into JavaScript in a future patch, so that it's possible to add additional points later and it'll calculate the average speed accordingly.

### CODE REVIEW

**Comment by espinosaluis** [comment]
I had reverted this commit because I realized the total distance information is wrong. I thought this issue was causing this, but it seems the bug was introduced in one of your previous commits.
This issue is more noticeable in long routes, especially if you check the total traveled distance in the last point of the route. Please fix this problem before new commits.

**Comment by espinosaluis** [comment]
Actually if you look at the total distance of the first point, it gives the correct total distance (the one that should be in the last point). However the total distance for the first point should be 0.

**Comment by xZise** [comment]
There are two issues:
1. The total distance is converted with inaccuracy from miles to kilometers which lead in one of my examples to a difference of about 150m. If you use the same conversion value (the given in the `distance`) function that difference goes away.
2. The distance of the first point isn't overwritten so it uses the value from the first iteration (which is for the total distance).

Anyway I'll provide a patch for both problems soon, although at some point it shouldn't be necessary to have two iterations.

**Comment by xZise** [comment]
Okay regarding the inaccuracy: The first loop calculates the distance in miles and then just uses 1.6 km/miles as a conversion factor. The second loop calculates the distance in kilometers and then uses 1.6 km/miles too to convert it back. The difference is that the distance calculated is not different by a factor of 1.6 but a bit of (as a statute mile is longer than 1.6 kilometers: 1 mi := 1760 yds := 5280 ft := 63360 in := 63360 in × 25.4 mm/in = 1609344 mm).

The distance is actually calculated in miles and converted to kilometers in the second loop by the `distance` function. So in the first loop the distance is “miles \* 1.6” and in the second it is “miles \* 1.609344”, the difference arises when the unit is set to miles. In the first loop it just uses the miles output and in the second it now does “miles \* 1.609344 / 1.6“.

**Comment by espinosaluis** [comment]
I see the same issue no matter if you select Imperial or Metric. It was working fine in the previous versions before your changes so at some point the bug was introduced.

**Comment by xZise** [comment]
Of course you'll see the issues in both conversions. `miles × 1.6 ≠ miles × 1.609344` (metric) and `miles ≠ miles × 1.6 ÷ 1.609344` (imperial). And the second issue is sort of unrelated to the conversion factors (as described in #50 the imperial variant should've worked longer).

**Comment by espinosaluis** [comment]
Yes, sir. I was just stating that so in case it would help you when you are debugging it, which I think it didn't because now it works only for imperial but still doesn't for the metric system.

**Comment by xZise** [comment]
Really?! I tested that patch and both issues described were fixed for me: The summary and balloon both showed the same value (the higher of the previous). And the first balloon is now showing 0 distance.

Because of the patch in #50, the summary distances are now higher (by about 0.6 %) but that is just because previously it was inaccurate when using the metric system and while the balloons have been more accurate for a while (at least for the metric value) the summary is now as accurate.

Or do you mean “now” before you merged #50? And if the issue persists could you be more specific what is the issue: Which value is wrong how, compared to what?

**Comment by espinosaluis** [comment]
I meant after #50. It's compared to the viewer before you started working on it. I have both versions installed on my web host.

Here it's how it looks before:
old

After #50:
new

**Comment by espinosaluis** [comment]
Notice that the time format has also changed.

**Comment by espinosaluis** [comment]
I'm also comparing it to the total distance I get on my app.

**Comment by espinosaluis** [comment]
Actually I think it's working now. If I set it to Imperial, I get 642.492 miles. If I convert that, I get 1,033.99 Km. So the conversion was incorrect in the old version.

**Comment by xZise** [comment]
Yeah it was inaccurate and used 1.6 miles/km instead of 1.609344 miles/km. If you convert the lower value you'll get the larger one: 1027.99÷1.6×1.609344=1033.99346

The time format looks interesting as it appears it swapped month and days. I'm going to look into that even though I'm not exactly sure how that can happen as I didn't touch the format itself.

**Comment by xZise** [comment]
Okay at some point after fcb8b95 this change appears and in both versions it follows the format. So my assumption is that somewhere in between it parses the datetime from the database differently. And at least in my case it is now parsing it correctly, so maybe you could check what your date format is and what string is actually correctly formatted.

**Comment by xZise** [comment]
Actually there is no change after fcb8b95 and that patch is already using the configured setting. Could you maybe tell from when your “before” screenshot is?

**Pull request merged**
