### PR TITLE
Restore reverted commits

### LINKED ISSUE #30: You need to logout if you happen to close the viewer
Once you have logged in, if you close the page and go back to the viewer, it won't remember that you are logged in and an empty map is shown and the user information is missing. Check attached image.

capture

### PR DESCRIPTION
**Pull request by xZise**
This is restoring the commits reverted recently. I reworked the commits so that fixes for bugs introduced by my patches are already incorporated into the original commits. So this should fix #30 and the other issues mentioned in #23 except for #29 (although I don't think my changes caused this issue).

Now if possible I want to check what is happening with regards to #22, and if I need to fix one of these patches. So please don't merge it yet.

### CODE REVIEW

**Comment by xZise** [comment]
Okay I want to check the PDO patch because it introduces `password_verify` and `password_hash` which will cause an error on PHP 5.5 installations. So I'll close it before you merge this unintentionally.

**Comment by espinosaluis** [comment]
Thanks for your hard work and for fixing all the mess I made.
I have been testing it, and these are my results.
- Opening a second viewer in a different tab it works now. I don't need to logout and login.
- Positions with icons are showing the right icon now (this includes the camera icon)
- When deleting a route, the route list is updated correctly.
- The issue with the bearings is still there, but I saw that you created a fix that I haven't tested yet.
- Some routes still don't show up. At this moment I have 44 routes on my database and there are 4 that don't show up. Just the background gray screen. I tried those with the old version and I can see them. I don't think there is nothing special about them. If there is something in particular that you think I should look into, let me know.

**Comment by xZise** [comment]
I have tried to delete a trip on the production instance (using a dummy entry and MySQL) and that worked too. Not sure if my patches had an issue which was fixed accidentally or if there wasn't actually an issue (e.g. trying to delete “Any” or “None” doesn't work obviously).

Regarding the four trips that don't work: I don't really know why as my test instance now uses trips with photos, comments and custom icons and that seems to work (as you stated too). What would be nice if you could change the owner of one of the trips to my “test” account (bobbot):

```
UPDATE trips SET FK_Users_ID = 44273 WHERE ID = ?;
UPDATE positions SET FK_Users_ID = 44273 WHERE FK_Trips_ID = ?;
```

Then I would be able to take a closer look.

**Comment by espinosaluis** [comment]
I think I just found out why they don't show up. It seems to happen if the route name has accented characters (á,é,í,ó,ú) or a single quote (')
I have one route with an accented character that works though, however all the routes that don't show up have that in common. Maybe it could also affect if a comment has a quote or accented character.

**Comment by espinosaluis** [comment]
Ok, after some more testing, I think the problem is with the single quote. If a route has a comment or description with a quote, then it won't show up. I think that's the problem.

**Comment by espinosaluis** [comment]
Actually I noticed there is a bug in my app related to that, too.

**Comment by xZise** [comment]
OH right yes… I don't “escape” the string. So for example if the comment is `foo's bar` then it'll add `comment: 'foo's bar'`. I need to find a way to fix this actually so that it'll add  `comment: 'foo\'s bar'`. Same happens if you have `foo\` as that will result in `comment: 'foo\'` and thus the string doesn't end there. Thank you for that totally forget that I needed to implement that (when I first wrote it I already thought that might happen but didn't consider that it's like this happens…).

**Comment by espinosaluis** [comment]
Yeah, it happens all the time. Actually the problem that I found on my app was the same thing.

**Comment by xZise** [comment]
And afaik might be `requests.php` also vulnerable to it but at least not because of the quote but because of the pipe character. Although in case also the apps might not work properly and I'd actually suggest a more commonly used format like JSON ;)

**Comment by espinosaluis** [comment]
Yeah, I'm afraid you're right. I didn't use the best approach there...

**Pull request merged**
