### PR TITLE
Revert "Prepare requests to switch to PDO"

### PR DESCRIPTION
**Pull request by espinosaluis**
Reverts espinosaluis/TrackMeViewer#81

New users cannot be created anymore. It returns "Incorrect password for user"

xZise, please be careful when modifying parts that could also affect the TrackMe clients (Requests.php is one of those files). Please try to test your changes by also using the client (I don't know if you are running this with Android, WM or Windows Phone) to be sure everything is still working the same.

### CODE REVIEW

**Comment by xZise** [comment]
Well I try testing as good as possible but human error. Would be nice if there is a test suite which could test that automatically.

Also this quickly reverting is kind of annoying as I now need to do quite some git wizardry just to redo all those changes. Couldn't you just give me some time to actually respond and write a patch? The reason for a versioning system like git is that you can easily select another version without that patch.

**Comment by xZise** [comment]
Also I don't actually test those changes using your app for two reasons:
1. I can't be sure what calls the app actually does and whether it is calling the parts I changed
2. It seems that I can't configure multiple servers at the same time, and I test it on a non-production server, so I'd have to reconfigure it every time.

And even then I'd need to actually test to create a new user. So instead I just call the page from my browser.

**Comment by espinosaluis** [comment]
Ok, next time I will not revert the changes until a couple of weeks later, in case you haven't been able to fix it by then. I'm sorry, I didn't know it was so complicated to redo all your changes.

I appreciate very much all the changes that you making, but for every one of your changes I have to do lots of things to be sure nothing is broken, so it's also a lot of work for me because basically I have to retest everything on the viewer. Now that you are also making modifications to some of the files used by the client (requests.php, export.php, upload.php, cloud.php as far as I can remember) it would help that at least you could test a little bit those changes. For example, if you make changes to user validation like you just did, take a look if you can still create new users from the client and the positions are uploaded correctly.

**Comment by xZise** [comment]
Well I'm a human and there might be stuff slipping through the cracks. And then there are a lot of edge cases. So I decided to check if we could use automated testing. The first tests (although they didn't test anything) are there: https://travis-ci.org/xZise/TrackMeViewer/builds/132919665

I'll try to have a few tests working and then will fix the issue mentioned above.

(And tbh I actually tested what would happen if the username was wrong and got the error which I thought was correct and totally forgot that it actually should create a user)

**Comment by espinosaluis** [comment]
Please don't take it so personal. I'm just asking you to test your changes from the app. That's all. 
I develop everyday for work and for TrackMe as a hobby and I make mistakes all the time. I won't say anything next time.

**Comment by xZise** [comment]
No that has nothing to do with me feeling attacked or something. But doing automatic testing just helps in finding errors like this one. Sure there might be still issues going through the cracks, but at least some parts don't need to be manually tested (which I find quite tedious personally as I'm never sure if I actually tested it properly).

**Pull request merged**
